version: '3.4'

networks:
  dev:
    driver: bridge

services:
  langvault.apigateway:
    image: docker.io/library/langvault.apigateway
    container_name: langvault.apigateway
    ports:
      - 4201:80
    build:
      context: .
      dockerfile: LangVault.ApiGateway/Dockerfile
    networks:
      - dev

  langvault.accounting:
    image: docker.io/library/langvault.accounting
    container_name: langvault.accounting
    # depends_on:
    #   - "langvault.db"
    ports:
      - 4203:80
    restart: always
    build:
      context: .
      dockerfile: LangVault.Accounting/LangVault.Accounting/Dockerfile
    networks:
      - dev

  langvault.management:
    tty: true
    image: docker.io/library/langvault.management
    container_name: langvault.management
    environment:
      - ConnectionStrings__DefaultConnection=host=langvault.db;database=LangVault;username=postgres;password=postgre123
    depends_on:
      - langvault.db
    ports:
      - 4205:80
    restart: always
    build:
      context: .
      dockerfile: LangVault.Management/LangVault.Management/Dockerfile
    networks:
      - dev

  # langvault.notifications.telegram:
  #   image: docker.io/library/langvault.notifications.telegram
  #   container_name: langvault.notifications.telegram
  #   ports:
  #     - 4207:80
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: LangVault.Notifications/Telegram/Dockerfile
  #   networks:
  #     - dev

  langvault.db:
    image: postgres:latest
    container_name: langvault.db
    environment:
      - POSTGRES_DB=LangVault
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre123
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    networks:
      - dev

  langvault.mq:
    image: rabbitmq:3.12.10-management
    container_name: langvault.mq
    hostname: langvault-queue
    volumes:
      - ./.containers/queue/data:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
